# Generated by Django 3.0.8 on 2020-11-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201103_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='dimension',
            field=models.CharField(max_length=20),
        ),
    ]
